name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python scripts/train.py
      - run: pytest tests/
      - run: flake8 app/ scripts/
      - uses: actions/upload-artifact@v4
        with:
          name: model
          path: |
            app/model.joblib
            app/scaler.joblib
            model_metrics.txt
