name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python scripts/train.py
      - run: pytest tests/ --maxfail=1
      - run: flake8 app scripts
      - uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: app/model.joblib
