name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python scripts/train.py
      - run: docker build -t ghcr.io/${{ github.repository }}:${{ github.ref_name }} .
      - run: docker run -d -p 8000:8000 ghcr.io/${{ github.repository }}:${{ github.ref_name }}
      - run: sleep 10 && curl -f localhost:8000/health
      - run: docker push ghcr.io/${{ github.repository }}:${{ github.ref_name }}
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            model_metrics.txt
            CHANGELOG.md
