name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python scripts/train.py
      - run: docker build -t ghcr.io/<org>/<repo>:${GITHUB_REF#refs/tags/} .
      - run: docker run --rm -p 8000:8000 ghcr.io/<org>/<repo>:${GITHUB_REF#refs/tags/} curl -s localhost:8000/health
      - run: docker push ghcr.io/<org>/<repo>:${GITHUB_REF#refs/tags/}
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          files: |
            model_metrics.txt
            CHANGELOG.md
